alter table public.topics
  add column if not exists revision_objectives text[] not null default '{}',
  add column if not exists revision_supplement_keys text[] not null default '{}';

with revision_content (topic_slug, revision_objectives, revision_supplement_keys) as (
  values
    ('1-1-programming-fundamentals', array['Use variables and constants to store values.', 'Use assignment to give a variable a value and update it.', 'Accept inputs and produce outputs.', 'Choose and use suitable integer, real, Boolean, character and string data types.', 'Cast data temporarily from one type to another and identify situations in which casting is useful.', 'Recognise and use the comparison operators ==, !=, <, <=, > and >=.', 'Recognise and use the arithmetic operators +, -, *, /, MOD, DIV and ^.', 'Recognise and use the Boolean operators AND, OR and NOT in program expressions.', 'Manipulate strings using concatenation and slicing.', 'Interpret and use the OCR string operations length, substring, left, right, upper, lower, ASC and CHR.', 'Generate and use random integer and real values.', 'Apply these fundamentals in a high-level programming language.']::text[], '{}'::text[]),
    ('1-2-sequence-and-selection', array['Explain and use sequence so instructions execute in the intended order.', 'Use selection to choose which instructions run according to a condition.', 'Create, interpret, correct, complete and refine IF, ELSEIF and ELSE selection.', 'Create and interpret CASE SELECT or SWITCH selection, including a default case.', 'Form selection conditions using comparison and Boolean operators.', 'Use nested selection when a problem requires decisions inside decisions.', 'Apply sequence and selection in a high-level programming language.']::text[], '{}'::text[]),
    ('1-3-iteration', array['Explain why iteration is used.', 'Distinguish count-controlled iteration from condition-controlled iteration.', 'Create, interpret, correct, complete and refine FOR loops.', 'Use a positive or negative step value in a FOR loop.', 'Create, interpret, correct, complete and refine WHILE loops.', 'Explain that a WHILE condition is checked before the loop body runs.', 'Create, interpret, correct, complete and refine DO UNTIL loops.', 'Explain that a DO UNTIL loop runs once before its condition is checked.', 'Choose a suitable loop type for a given problem.', 'Use nested iteration and nesting that combines iteration with selection.', 'Apply iteration in a high-level programming language.']::text[], '{}'::text[]),
    ('1-4-arrays', array['Explain why arrays are used when solving problems.', 'Declare, populate, access and update one-dimensional arrays.', 'Declare, populate, access and update two-dimensional arrays.', 'Use zero-based indexes when working with OCR Exam Reference Language arrays.', 'Explain that OCR arrays are fixed-length or static structures.', 'Explain that an OCR array stores values of one data type.', 'Explain how records store related fields about one item.', 'Use two-dimensional arrays to represent table-like data made from fields and records.', 'Pass arrays into subprograms and return arrays where appropriate.', 'Apply arrays and records in a high-level programming language.']::text[], '{}'::text[]),
    ('1-5-procedures-and-functions', array['Explain how subprograms help produce structured and maintainable code.', 'Create and call procedures with and without parameters.', 'Create and call functions with and without parameters.', 'Return a value from a function and store or use that returned value.', 'Distinguish a function from a procedure.', 'Choose when a function or procedure is appropriate.', 'Use local variables and constants within subprograms.', 'Explain and use global variables and constants where appropriate.', 'Pass arrays to subprograms and return arrays where appropriate.', 'Apply functions and procedures in a high-level programming language.']::text[], '{}'::text[]),
    ('1-6-text-files', array['Explain why programs read data from and write data to files.', 'Create a new text file.', 'Open a text file and retain its file handle in a variable.', 'Read lines from a text file.', 'Write lines to a text file.', 'Test for the end of a file when reading multiple lines.', 'Close a file after use.', 'Combine open, read, write and close operations in a working program.', 'Apply basic file handling in a high-level programming language.']::text[], '{}'::text[]),
    ('1-7-introduction-to-sql', array['Explain that SQL can be used to search stored data.', 'Use SELECT to identify the fields to return.', 'Use FROM to identify the table to search.', 'Use WHERE to filter records using a condition.', 'Combine SELECT, FROM and WHERE in a simple query.', 'Interpret and write simple SQL queries in a given scenario.']::text[], '{}'::text[]),
    ('1-8-defensive-design', array['Explain how defensive design anticipates likely misuse and unexpected inputs.', 'Design a program that caters for the likely range of input values.', 'Validate input and deal appropriately with invalid data.', 'Explain how authentication confirms a user''s identity.', 'Design and implement simple authentication such as a username and password check.', 'Improve maintainability through meaningful naming conventions.', 'Use consistent indentation.', 'Add useful comments and explain why commenting helps maintenance.', 'Use subprograms to make code easier to understand, test and maintain.', 'Apply defensive design techniques in a high-level programming language.']::text[], '{}'::text[]),
    ('1-9-errors-and-testing', array['Explain the purpose of testing.', 'Distinguish iterative testing during development from final or terminal testing at the end of production.', 'Identify syntax errors and explain that they break the language''s grammatical rules and prevent code from running or being translated.', 'Identify logic errors and explain that they cause unexpected output.', 'Select normal test data that should be accepted.', 'Select boundary test data at the edge of the valid range.', 'Select invalid test data of the correct type that should be rejected.', 'Select erroneous test data of the wrong type that should be rejected.', 'Choose suitable test data for a given scenario and justify the choices.', 'Create and complete a test plan with expected and actual results.', 'Use test results to correct and refine algorithms or programs.']::text[], '{}'::text[]),
    ('1-10-translators-and-facilities', array['Describe the characteristics and purposes of high-level languages.', 'Describe the characteristics and purposes of low-level languages.', 'Compare high-level and low-level languages.', 'Explain why translators are needed.', 'Describe how a compiler translates a program.', 'Describe how an interpreter translates and executes a program.', 'Compare the benefits and drawbacks of compilers and interpreters.', 'Select a suitable translator for a given scenario and justify the choice.']::text[], '{}'::text[]),
    ('1-11-ides', array['Explain the purpose of an Integrated Development Environment.', 'Describe how an editor helps a programmer write and change code.', 'Describe how error diagnostics help identify problems.', 'Describe how a run-time environment helps execute and test code.', 'Describe how translators are provided or used within an IDE.', 'Explain how each IDE tool or facility supports program development.', 'Use a range of these tools in at least one IDE.']::text[], '{}'::text[]),
    ('2-1-architecture-of-the-cpu', array['Explain the purpose of the CPU.', 'Describe the fetch-execute cycle and the actions at each stage.', 'Describe the purpose and role of the Arithmetic Logic Unit.', 'Describe the purpose and role of the Control Unit.', 'Describe the purpose and role of cache in the CPU.', 'Explain the role of registers during the fetch-execute cycle.', 'Describe the Von Neumann architecture.', 'State the purpose of the Memory Address Register, Memory Data Register, Program Counter and Accumulator.', 'Identify whether each named register stores data or an address.', 'Explain the difference between storing data and storing an address.']::text[], '{}'::text[]),
    ('2-2-cpu-performance-and-embedded-systems', array['Explain what CPU clock speed means.', 'Explain how changing clock speed can affect system performance.', 'Explain how changing cache size can affect system performance.', 'Explain how changing the number of CPU cores can affect performance.', 'Analyse the combined effect of CPU characteristics in a given scenario.', 'Explain what an embedded system is and its purpose.', 'Describe typical characteristics of embedded systems.', 'Recognise and give examples of embedded systems.', 'Apply knowledge of embedded systems to unfamiliar scenarios.']::text[], '{}'::text[]),
    ('2-3-primary-memory', array['Explain why a computer needs primary storage.', 'Explain that primary storage normally includes RAM and ROM.', 'Describe the purpose and key characteristics of RAM.', 'Describe the purpose and key characteristics of ROM.', 'Compare RAM and ROM.', 'Explain the purpose of ROM in a computer system.', 'Explain the purpose of RAM in a computer system.', 'Explain why virtual memory may be needed.', 'Explain how virtual memory transfers data between RAM and secondary storage when RAM is full.', 'Explain the role of cache as primary storage.']::text[], '{}'::text[]),
    ('2-4-secondary-storage', array['Explain why computers need secondary storage.', 'Recognise optical, magnetic and solid-state storage.', 'Describe the differences between optical, magnetic and solid-state storage devices and media.', 'Compare storage devices and media by capacity.', 'Compare storage devices and media by speed.', 'Compare storage devices and media by portability.', 'Compare storage devices and media by durability.', 'Compare storage devices and media by reliability.', 'Compare storage devices and media by cost.', 'Recommend suitable storage for a given application and justify the choice.']::text[], '{}'::text[]),
    ('3-1-operating-systems', array['Explain the purpose of an operating system.', 'Describe the features and purpose of a user interface.', 'Explain how an operating system allocates memory to applications.', 'Explain how memory management supports multitasking.', 'Explain how an operating system manages transfers between memory.', 'Explain how an operating system manages peripherals and device drivers.', 'Explain that data transfers between devices and the processor need to be managed.', 'Describe user-management functions including accounts, access rights and security.', 'Describe file-management functions including naming, folders, moving and saving files.', 'Apply operating-system knowledge to a given scenario.']::text[], '{}'::text[]),
    ('3-2-utility-software', array['Explain the purpose of utility software.', 'Explain that utility software performs housekeeping and additional tasks that may not be carried out by the operating system.', 'Explain the purpose of encryption software and why it is needed.', 'Explain the purpose of defragmentation software and why it is needed.', 'Explain the purpose of data-compression software and why it is needed.', 'Recommend suitable utility software for a given need.']::text[], '{}'::text[]),
    ('4-1-units-and-binary-numbers', array['Define bit, nibble and byte.', 'Recall that a nibble contains 4 bits and a byte contains 8 bits.', 'Use kilobyte, megabyte, gigabyte, terabyte and petabyte.', 'Convert between data-storage units using the OCR decimal definitions.', 'Accept and interpret calculations that use 1,024 where stated.', 'Explain why data must be converted to binary for computer processing.', 'Explain that storage devices have fixed capacities.', 'Calculate the storage capacity required for a given collection of files.', 'Convert positive denary whole numbers from 0 to 255 into binary values of up to 8 bits.', 'Convert binary values of up to 8 bits into denary.', 'Identify the most significant bit and least significant bit.', 'Recognise that leading zeroes do not change a binary value.']::text[], '{}'::text[]),
    ('4-2-binary-arithmetic-and-hexadecimal', array['Add two binary integers of up to 8 bits.', 'Identify and explain overflow errors produced by binary addition.', 'Convert positive denary whole numbers into two-digit hexadecimal values.', 'Convert two-digit hexadecimal values into denary.', 'Convert binary integers into hexadecimal.', 'Convert hexadecimal values into binary.', 'Work within OCR''s ranges of 00000000 to 11111111, denary 0 to 255 and hexadecimal 00 to FF.', 'Carry out left and right binary shifts.', 'Explain the effect of left and right shifts on a binary value.']::text[], '{}'::text[]),
    ('4-3-logic-gates-and-truth-tables', array['Recall and use the truth table for an AND gate.', 'Recall and use the truth table for an OR gate.', 'Recall and use the truth table for a NOT gate.', 'Recognise the standard symbols for AND, OR and NOT gates.', 'Create, complete and edit simple logic diagrams.', 'Create, complete and edit truth tables.', 'Combine more than one Boolean operator or logic gate.', 'Apply logical operators in truth tables to solve a problem.', 'Interpret alternative valid notation such as 1/0 or True/False.']::text[], array['logic_gates_reference']::text[]),
    ('4-4-characters', array['Explain how binary codes represent characters.', 'Define the term character set.', 'Explain how the number of bits per character limits the number of characters that can be represented.', 'Compare ASCII and Unicode and explain the effect of each character set.', 'Explain that character sets are logically ordered.', 'Interpret 8-bit ASCII values when they are provided in an examination.', 'Calculate text-file size from bits per character and number of characters.', 'Use ASC and CHR conversions in OCR Exam Reference Language.']::text[], '{}'::text[]),
    ('4-5-images', array['Explain how an image is represented as a grid of pixels in binary.', 'Explain that each pixel''s colour is represented by a binary code.', 'Explain how colour depth affects image quality and file size.', 'Explain how image resolution affects image quality and file size.', 'Explain the purpose of image metadata and give examples such as width and height.', 'Calculate image-file size using colour depth x image height x image width.', 'Apply image-representation knowledge to a given scenario.']::text[], '{}'::text[]),
    ('4-6-sound', array['Explain why analogue sound must be converted into binary for storage.', 'Explain how sound is sampled and stored digitally.', 'Define sample rate and state that it is measured in hertz.', 'Define duration in seconds.', 'Define bit depth as the number of bits used to store each sample.', 'Explain how sample rate affects playback quality and file size.', 'Explain how duration affects file size.', 'Explain how bit depth affects playback quality and file size.', 'Calculate sound-file size using sample rate x duration x bit depth.', 'Apply sound-representation knowledge to a given scenario.']::text[], '{}'::text[]),
    ('4-7-data-compression-file-formats-and-encryption', array['Explain why files may need to be compressed.', 'Identify scenarios in which compression is useful.', 'Explain the principle of lossy compression.', 'Explain the principle of lossless compression.', 'Compare the advantages and disadvantages of lossy and lossless compression.', 'Explain the effect of lossy and lossless compression on a file.', 'Explain the principle of encryption for securing data.', 'Explain the purpose of encryption utility software.']::text[], '{}'::text[]),
    ('5-1-lan', array['Define a Local Area Network.', 'Describe the characteristics of a LAN.', 'Recognise common examples of LANs.', 'Explain how the number of connected devices can affect performance.', 'Explain how bandwidth can affect performance.', 'Explain other relevant factors that affect network performance in a given scenario.', 'Apply knowledge of LANs to recommend or evaluate a network.']::text[], '{}'::text[]),
    ('5-2-lan-hardware', array['Explain the role of a wireless access point.', 'Explain the role of a router.', 'Explain the role of a switch.', 'Explain the role of a Network Interface Controller or Card.', 'Explain the role of transmission media.', 'Select the hardware needed to connect stand-alone computers into a LAN.', 'Apply knowledge of network hardware to a given scenario.']::text[], '{}'::text[]),
    ('5-3-lan-topologies', array['Describe a star network topology.', 'Describe a mesh network topology.', 'Compare the advantages and disadvantages of star and mesh topologies.', 'Recommend a suitable topology for a given scenario and justify the choice.']::text[], '{}'::text[]),
    ('5-4-the-internet-and-wan', array['Define a Wide Area Network.', 'Describe the characteristics of a WAN and give common examples.', 'Explain that the Internet is a worldwide network of computer networks.', 'Explain that the Domain Name Service uses multiple Domain Name Servers.', 'Explain how DNS converts a URL into an IP address.', 'Explain the purpose of hosting.', 'Explain the roles of web servers and web clients.', 'Explain that cloud computing provides remote services such as storage, software and processing.', 'Compare the advantages and disadvantages of cloud computing.', 'Apply knowledge of the Internet and WANs to a given scenario.']::text[], '{}'::text[]),
    ('5-5-client-server-and-p2p-networks', array['Describe the roles of computers in a client-server network.', 'Explain that servers provide services such as web pages and file storage.', 'Explain that clients request and use services from servers.', 'Describe the roles of computers in a peer-to-peer network.', 'Compare client-server and peer-to-peer networks.', 'Select a suitable network model for a scenario and justify the choice.']::text[], '{}'::text[]),
    ('5-6-network-protocols-and-layers', array['Compare wired and wireless network connections.', 'Explain the use of Ethernet, Wi-Fi and Bluetooth as connection modes.', 'Recommend one or more connection modes for a scenario.', 'Explain the principle of encryption for securing data across a network connection.', 'Describe the format and purpose of IPv4 and IPv6 addresses.', 'Describe the format and use of a MAC address within a network.', 'Explain that a standard supplies rules that allow hardware and software from different producers to interact.', 'Explain that a communication protocol is a set of rules for transferring data.', 'State the purpose and key features of TCP/IP, HTTP, HTTPS, FTP, POP, IMAP and SMTP.', 'Explain why different protocols are used for different purposes.', 'Explain how protocol layers are used and the benefits of a layered approach.', 'Apply protocol and connection knowledge to a given scenario.']::text[], '{}'::text[]),
    ('6-1-network-threats', array['Explain threats posed to devices, systems and networks.', 'Explain how malware attacks are used and their purpose.', 'Explain social engineering, including phishing and people as a weak point.', 'Explain how brute-force attacks are used and their purpose.', 'Explain how denial-of-service attacks are used and their purpose.', 'Explain how data interception and theft occur and their purpose.', 'Explain the concept of SQL injection.', 'Identify a likely form of attack from a scenario.']::text[], '{}'::text[]),
    ('6-2-preventing-vulnerabilities', array['Explain how penetration testing identifies or reduces vulnerabilities.', 'Explain how anti-malware software limits malware threats.', 'Explain how firewalls limit network threats.', 'Explain how user access levels reduce risk.', 'Explain how strong passwords reduce risk.', 'Explain how encryption limits the impact of data interception and theft.', 'Explain how physical security protects systems and data.', 'Match each prevention method to the attacks it may limit or prevent.', 'Recommend suitable prevention methods for a scenario and justify the choices.']::text[], '{}'::text[]),
    ('7-1-computational-thinking', array['Define abstraction.', 'Use abstraction to remove unnecessary detail from a problem.', 'Define decomposition.', 'Decompose a problem into smaller subproblems.', 'Define algorithmic thinking.', 'Use algorithmic thinking to form a step-by-step solution.', 'Explain how abstraction, decomposition and algorithmic thinking help define and refine problems.']::text[], '{}'::text[]),
    ('7-2-searching-algorithms', array['Describe the main steps of a linear search.', 'Apply a linear search to a data set.', 'Identify a linear search from code, pseudocode or OCR Exam Reference Language.', 'Describe the main steps of a binary search.', 'Explain that binary search requires ordered data.', 'Apply a binary search to a data set.', 'Identify a binary search from code, pseudocode or OCR Exam Reference Language.', 'Compare linear and binary search for a given scenario.']::text[], '{}'::text[]),
    ('7-3-sorting-algorithms', array['Describe the main steps and code segments of bubble sort.', 'Apply bubble sort to a data set.', 'Identify bubble sort from code, pseudocode or OCR Exam Reference Language.', 'Describe the main steps and code segments of merge sort.', 'Apply merge sort to a data set.', 'Identify merge sort from code, pseudocode or OCR Exam Reference Language.', 'Describe the main steps and code segments of insertion sort.', 'Apply insertion sort to a data set.', 'Identify insertion sort from code, pseudocode or OCR Exam Reference Language.', 'Identify any prerequisites of a given sorting algorithm.']::text[], '{}'::text[]),
    ('7-4-flowcharts', array['Recognise terminal, process, input/output, decision, subprogram and flow line symbols.', 'Interpret an algorithm represented as a flowchart.', 'Create a flowchart for a given problem.', 'Complete, correct and refine a flowchart.', 'Represent sequence, selection and iteration in a flowchart.', 'Identify inputs, processes and outputs before designing a flowchart.', 'Produce simple structure diagrams showing problem sections and the links between them.']::text[], array['flowchart_symbols_reference']::text[]),
    ('7-5-pseudocode', array['Interpret algorithms written in pseudocode.', 'Create algorithms using clear pseudocode.', 'Complete, correct and refine pseudocode.', 'Express sequence, selection, iteration, arrays and subprograms in pseudocode.', 'Translate between natural-language requirements, pseudocode, flowcharts and program code.', 'Distinguish informal pseudocode from the more precise OCR Exam Reference Language.']::text[], '{}'::text[]),
    ('7-6-interpreting-algorithms', array['Identify the inputs, processes and outputs of a problem.', 'Interpret algorithms represented in pseudocode, flowcharts, OCR Exam Reference Language or a high-level language.', 'Create, correct, complete and refine an algorithm.', 'Identify syntax and logic errors in code and suggest fixes.', 'Create and use trace tables to follow an algorithm.', 'Trace variable values, outputs, selection paths and loop iterations.', 'Interpret nested selection and iteration.', 'Compare an algorithm with its requirements and identify improvements.']::text[], '{}'::text[]),
    ('8-1-ethical-and-cultural-issues', array['Explain how digital technology can create ethical issues.', 'Explain how digital technology can create cultural issues.', 'Give a range of examples of technology affecting individuals and wider society.', 'Discuss positive and negative impacts of digital technology.', 'Consider different stakeholders and viewpoints.', 'Apply ethical and cultural considerations to unfamiliar scenarios.', 'Produce a balanced discussion supported by relevant examples.']::text[], '{}'::text[]),
    ('8-2-environmental-issues', array['Explain how manufacturing digital devices affects the environment.', 'Explain how using digital technology affects energy consumption.', 'Explain issues caused by electronic waste and disposal.', 'Explain how digital technology may reduce environmental impact.', 'Discuss positive and negative environmental effects in a given scenario.', 'Consider environmental consequences when evaluating a digital solution.']::text[], '{}'::text[]),
    ('8-3-legislation-and-privacy', array['Explain how digital technology creates legal and privacy issues.', 'Explain the purpose of the Data Protection Act 2018 and the actions it allows or prohibits.', 'Explain the purpose of the Computer Misuse Act 1990 and the actions it allows or prohibits.', 'Explain the purpose of the Copyright, Designs and Patents Act 1988 and the actions it allows or prohibits.', 'Explain why software must be licensed.', 'Describe open-source licensing, including access to and modification of source code.', 'Describe proprietary licensing, including restricted source-code access and typical off-the-shelf purchase.', 'Compare the benefits and drawbacks of open-source and proprietary software.', 'Recommend a suitable software licence for a scenario and justify the choice.', 'Discuss legal and privacy impacts of digital technology in context.']::text[], '{}'::text[])
)
update public.topics as topic
set
  revision_objectives = revision_content.revision_objectives,
  revision_supplement_keys = revision_content.revision_supplement_keys,
  updated_at = now()
from revision_content, public.units as unit, public.subjects as subject
where topic.slug = revision_content.topic_slug
  and topic.unit_id = unit.id
  and unit.subject_id = subject.id
  and subject.slug = 'ocr-gcse-computer-science';
